<wsdl:definitions xmlns:ns1="http://www.PCO.com/Credit/RiskAssessment/Response_v1.xsd" xmlns:tns="http://ougwebcomponent.components.oug.osgi.scorex.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:oug="http://ougwebcomponent.components.oug.osgi.scorex.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="Untitled" targetNamespace="http://ougwebcomponent.components.oug.osgi.scorex.com/">
    <wsdl:types>
        <xs:schema xmlns="http://ougwebcomponent.components.oug.osgi.scorex.com/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ougwebcomponent.components.oug.osgi.scorex.com/" elementFormDefault="qualified" attributeFormDefault="unqualified">
		<xs:element name="ougWS" type="tns:ougWS"/>
      <xs:element name="Output" type="tns:Output"/>
             <xs:complexType name="Output">
                     <xs:sequence>
                           <xs:element name="ApplicationDetails">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="T24ApplicationID" type="xs:string"></xs:element>
                                             <xs:element name="PCOApplicationID" type="xs:int"></xs:element>
                                             <xs:element name="TypeOfApplication" type="xs:string"></xs:element>
                                             <xs:element name="DateApplicationUpdated" type="xs:int"></xs:element>
                                             <xs:element name="TimeApplicationUpdated" type="xs:int"></xs:element>
                                             <xs:element name="ReprocessCount" type="xs:int"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="Input">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="DecisionCategory" type="xs:string"></xs:element>
                                             <xs:element name="DecisionText" type="xs:string"></xs:element>
                                             <xs:element name="RateKey" type="xs:string"></xs:element>
                                             <xs:element name="CardTypeAllocated" type="xs:string"></xs:element>
                                             <xs:element name="CreditScore" type="xs:int"></xs:element>
                                             <xs:element name="AssignedLimit" type="xs:int"></xs:element>
                                             <xs:element name="MaxBOIBorrowingAmt" type="xs:double"></xs:element>
                                             <xs:element name="TotalGroupExposure" type="xs:double"></xs:element>
                                             <xs:element name="RiskAdjustedAPR" type="xs:double"></xs:element>
                                             <xs:element name="AssignedShadowLimit" type="xs:int"></xs:element>
                                             <xs:element name="CurrentAccountSubProductType" type="xs:string"></xs:element>
                                             <xs:element name="NewMonthlyRepayments" type="xs:double"></xs:element>
                                             <xs:element name="CreditGrade" type="xs:string"></xs:element>
                                             <xs:element name="NetMonthlyIncome" type="xs:double"></xs:element>
                                             <xs:element name="MonthlyCredCommitments_Rev" type="xs:double"></xs:element>
                                             <xs:element name="MonthlyCredCommitments_NonRev" type="xs:double"></xs:element>
                                             <xs:element name="MonthlyHouseholdExpenditure" type="xs:int"></xs:element>
                                             <xs:element name="MonthlyAvailableResidualIncome" type="xs:int"></xs:element>
                                             <xs:element name="AffordableCreditLimit" type="xs:int"></xs:element>
                                             <xs:element name="ReferenceOfMostRecentApplication" type="xs:string"></xs:element>
                                             <xs:element name="CounterOffers">
                                                   <xs:complexType>
                                                         <xs:sequence>
                                                               <xs:element name="CounterOffer1">
                                                                     <xs:complexType>
                                                                           <xs:sequence>
                                                                                 <xs:element name="Amount" type="xs:double"></xs:element>
                                                                                 <xs:element name="Term" type="xs:int"></xs:element>
                                                                                 <xs:element name="APR" type="xs:double"></xs:element>
                                                                           </xs:sequence>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                         </xs:sequence>
                                                   </xs:complexType>
                                             </xs:element>
                                             <xs:element name="SpareDecisionField1" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField2" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField3" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField4" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField5" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField6" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField7" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField8" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField9" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField10" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField11" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField12" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField13" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField14" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField15" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField16" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField17" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField18" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField19" type="xs:string"></xs:element>
                                             <xs:element name="SpareDecisionField20" type="xs:string"></xs:element>
                                             <xs:element name="ReasonCodes">
                                                   <xs:complexType>
                                                         <xs:sequence>
                                                               <xs:element name="ReasonCode1">
                                                                     <xs:complexType>
                                                                           <xs:sequence>
                                                                                 <xs:element name="Code" type="xs:string"></xs:element>
                                                                                 <xs:element name="Text" type="xs:string"></xs:element>
                                                                           </xs:sequence>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                         </xs:sequence>
                                                   </xs:complexType>
                                             </xs:element>
                                             <xs:element name="Queues">
                                                   <xs:complexType>
                                                         <xs:sequence>
                                                               <xs:element name="Queue1" type="xs:string"></xs:element>
                                                         </xs:sequence>
                                                   </xs:complexType>
                                             </xs:element>
                                             <xs:element name="CorrespondenceLetterCodes">
                                                   <xs:complexType>
                                                         <xs:sequence>
                                                               <xs:element name="LetterCode1" type="xs:string"></xs:element>
                                                         </xs:sequence>
                                                   </xs:complexType>
                                             </xs:element>
                                             <xs:element name="NarrativeCodes">
                                                   <xs:complexType>
                                                         <xs:sequence>
                                                               <xs:element name="NarrativeCode" type="xs:string"></xs:element>
                                                         </xs:sequence>
                                                   </xs:complexType>
                                             </xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="BaselResults">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="PDScore" type="xs:int"></xs:element>
                                             <xs:element name="PD" type="xs:double"></xs:element>
                                             <xs:element name="PDPool" type="xs:int"></xs:element>
                                             <xs:element name="EAD" type="xs:double"></xs:element>
                                             <xs:element name="LGD" type="xs:double"></xs:element>
                                             <xs:element name="EL" type="xs:double"></xs:element>
                                             <xs:element name="Correlation" type="xs:double"></xs:element>
                                             <xs:element name="RequiredCapitalK" type="xs:double"></xs:element>
                                             <xs:element name="RWA" type="xs:double"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="Error">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="Code" type="xs:string"></xs:element>
                                             <xs:element name="Message" type="xs:string"></xs:element>
                                             <xs:element name="Source" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="BureauInformation">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="DMIdentifier" type="xs:string"></xs:element>
                                             <xs:element name="PreviousDMIdentifiers">
                                                   <xs:complexType>
                                                         <xs:sequence>
                                                               <xs:element name="DMID1" type="xs:string"></xs:element>
                                                         </xs:sequence>
                                                   </xs:complexType>
                                             </xs:element>
                                             <xs:element name="BureauDetails">
                                                   <xs:complexType>
                                                         <xs:sequence>
                                                               <xs:element name="CustomerId" type="xs:string"></xs:element>
                                                               <xs:element name="CRONumber" type="xs:string"></xs:element>
                                                               <xs:element name="ApplicantEntryOnInput" type="xs:int"></xs:element>
                                                               <xs:element name="BestCustomerInd" type="xs:string"></xs:element>
                                                               <xs:element name="ConsolidMarketClass" type="xs:string"></xs:element>
                                                               <xs:element name="CCRReference" type="xs:string"></xs:element>
                                                               <xs:element name="ICBReference" type="xs:string"></xs:element>
                                                               <xs:element name="IndivOrCompanyInd" type="xs:string"></xs:element>
                                                               <xs:element name="IndividualDOBMatchedToInput" type="xs:string"></xs:element>
                                                               <xs:element name="GlobalFicoScore" type="xs:string"></xs:element>
                                                               <xs:element name="CRIFScore" type="xs:string"></xs:element>
                                                               <xs:element name="RawToCodedBlock">
                                                                     <xs:complexType>
                                                                           <xs:sequence>
                                                                                 <xs:element name="CodedBlockPlaceholder1" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder2" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder3" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder4" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder5" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder6" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder7" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder8" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder9" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder10" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder11" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder12" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder13" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder14" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder15" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder16" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder17" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder18" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder19" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder20" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder21" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder22" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder23" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder24" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder25" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder26" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder27" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder28" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder29" type="xs:string"></xs:element>
                                                                                 <xs:element name="CodedBlockPlaceholder30" type="xs:string"></xs:element>
                                                                           </xs:sequence>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                               <xs:element name="GeneratedCriteria">
                                                                     <xs:complexType>
                                                                           <xs:sequence>
                                                                                 <xs:element name="CoarseGrading" type="xs:int"></xs:element>
                                                                                 <xs:element name="NoRestrAccPercOfAll" type="xs:int"></xs:element>
                                                                                 <xs:element name="NoRestrUnsecLoanAccPercOfAll" type="xs:int"></xs:element>
                                                                                 <xs:element name="NoRestrCCAccPercOfAll" type="xs:int"></xs:element>
                                                                                 <xs:element name="NoRestrUnsecLoanAccBalGT1000PercOfAll" type="xs:int"></xs:element>
                                                                                 <xs:element name="NoRestrCCAccBalGT500PercOfAll" type="xs:int"></xs:element>
                                                                                 <xs:element name="NoActiveAccUpToDatePercAll" type="xs:int"></xs:element>
                                                                                 <xs:element name="NoActiveBankAccUpToDatePercAll" type="xs:int"></xs:element>
                                                                                 <xs:element name="NoActiveCCAccUpToDatePercAll" type="xs:int"></xs:element>
                                                                                 <xs:element name="NoActiveAcc2PlusL1MPercOfAll" type="xs:int"></xs:element>
                                                                                 <xs:element name="NoActiveBankAcc2PlusL1MPercOfAll" type="xs:int"></xs:element>
                                                                                 <xs:element name="NoActiveCCAcc2PlusL1MPercOfAll" type="xs:int"></xs:element>
                                                                                 <xs:element name="ActiveRevBalPercLimitL1MtoL3MRatio" type="xs:int"></xs:element>
                                                                                 <xs:element name="ActiveRevBalPercLimitL1MtoL10toL12MRatio" type="xs:int"></xs:element>
                                                                                 <xs:element name="ActiveRevBalPercLimitL3MtoL10toL12MRatio" type="xs:int"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder1" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder2" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder3" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder4" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder5" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder6" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder7" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder8" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder9" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder10" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder11" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder12" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder13" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder14" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder15" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder16" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder17" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder18" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder19" type="xs:string"></xs:element>
                                                                                 <xs:element name="GeneratedCriteriaPlaceholder20" type="xs:string"></xs:element>
                                                                           </xs:sequence>
                                                                     </xs:complexType>
                                                               </xs:element>
                                                         </xs:sequence>
                                                   </xs:complexType>
                                             </xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                     </xs:sequence>
               </xs:complexType>
				<xs:complexType name="ougWS">
					  <xs:sequence>
						<xs:element type="xs:string" name="workflow_name"/>
						<xs:element name="data_flux" maxOccurs="unbounded" minOccurs="0">
						  <xs:annotation>
							<xs:documentation>Workflow Name (e.g. New Application)</xs:documentation>
						  </xs:annotation>
						  <xs:complexType>
							<xs:sequence>
							  <xs:element type="xs:string" name="item" maxOccurs="unbounded" minOccurs="0">
								<xs:annotation>
								  <xs:documentation>End Client Specific ID (for each Tenant)  Service ID (e.g. NEWAPP)  Username for Each PCO User  User Encrypted Password  Input Data for PCO Enclosed with a CDATA Block</xs:documentation>
								</xs:annotation>
							  </xs:element>
							</xs:sequence>
						  </xs:complexType>
						</xs:element>
					  </xs:sequence>
					</xs:complexType>
        </xs:schema>
    </wsdl:types>
    <wsdl:service name="AssessingCreditRisk">
        <wsdl:port name="SOAPEventSource" binding="tns:SOAPEventSourceBinding">
            <soap:address location="http://localhost:8085/AssessingCreditRisk/SOAPEventSource"/>
        </wsdl:port>
    </wsdl:service>
    <wsdl:portType name="PCOCreditRiskPort">
        <wsdl:operation name="PCOCreditRiskAssessment">
            <wsdl:input message="tns:Request"/>
            <wsdl:output message="tns:Response"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SOAPEventSourceBinding" type="tns:PCOCreditRiskPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="PCOCreditRiskAssessment">
            <soap:operation style="document" soapAction="/AssessingCreditRisk/SOAPEventSource"/>
            <wsdl:input>
                <soap:body use="literal" parts="part1"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="part2"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:message name="Request">
        <wsdl:part name="part1" element="oug:ougWS"/>
    </wsdl:message>
    <wsdl:message name="Response">
        <wsdl:part name="part2" element="Output"/>
    </wsdl:message>
</wsdl:definitions>
